"""Generate local persona profiles from the conversation app's bundled personas.

For each upstream persona in reachy_mini_conversation_app/profiles/<name>/ (except `default`,
which our base profiles replace, and hidden ones), write two profiles:

  local_backend/profiles/local_<name>/profile.md       offline tools (like local_reachy)
  local_backend/profiles/local_<name>_web/profile.md   plus the online tools (like local_reachy_web)

Each gets the persona's own personality text, our tool list, our tool/movement/speech rules
(copied from the base profile, so personas behave like Reachy with a different character), and a
voice. Generated files are committed; tests/test_local_stack.py checks they are up to date.
Re-run after changing a base profile:

    python3 local_backend/make_personas.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
UPSTREAM = HERE.parent / "reachy_mini_conversation_app" / "profiles"
OUT = HERE / "profiles"
BASES = {"": "local_reachy", "_web": "local_reachy_web"}

# Qwen3-TTS CustomVoice speakers in our GGUF: Aiden, Ryan, Dylan, Eric, Ono_Anna, Serena, Sohee,
# Uncle_Fu, Vivian. The base profiles use Aiden. Change freely.
VOICES = {
    "bored_teenager": "Dylan",
    "captain_circuit": "Ryan",
    "chess_coach": "Eric",
    "cosmic_kitchen": "Vivian",
    "hype_bot": "Aiden",
    "mad_scientist_assistant": "Eric",
    "mars_rover": "Aiden",
    "nature_documentarian": "Uncle_Fu",
    "noir_detective": "Ryan",
    "sorry_bro": "Dylan",
    "time_traveler": "Serena",
    "victorian_butler": "Ryan",
}
SHARED_FROM, SHARED_TO = "## TOOL & MOVEMENT RULES", "## FINAL REMINDER"


def split_profile(text: str) -> tuple[str, str]:
    """(front matter, body) of a `+++ toml +++ body` profile."""
    _, front, body = text.split("+++", 2)
    return front, body.strip()


def tool_names(front: str) -> list[str]:
    return re.findall(r'"([a-z_]+)"', front.split("default_tools", 1)[1].split("]", 1)[0])


def personas() -> list[str]:
    names = []
    for p in sorted(UPSTREAM.glob("*/profile.md")):
        front, _ = split_profile(p.read_text())
        if p.parent.name == "default" or re.search(r"^\s*hidden\s*=\s*true", front, re.M):
            continue
        names.append(p.parent.name)
    return names


def render(name: str, suffix: str) -> str:
    base_front, base_body = split_profile((OUT / BASES[suffix] / "profile.md").read_text())
    _, persona_body = split_profile((UPSTREAM / name / "profile.md").read_text())
    tools = tool_names(base_front)
    shared = base_body[base_body.index(SHARED_FROM):base_body.index(SHARED_TO)].strip()
    tool_lines = "".join(f'  "{t}",\n' for t in tools)
    return (
        "+++\n"
        f"# Generated by local_backend/make_personas.py from reachy_mini_conversation_app/profiles/{name}\n"
        f"# and local_backend/profiles/{BASES[suffix]}. Edit those (or the generator), not this file.\n"
        "schema_version = 1\n"
        f'voice = "{VOICES.get(name, "Aiden")}"\n'
        f"default_tools = [\n{tool_lines}]\n"
        "+++\n\n"
        "## PERSONA\n"
        f"You are Reachy Mini, a small desk robot, currently playing this character:\n\n{persona_body}\n\n"
        "Stay in character, but never let the character stop you from using your tools or following the rules "
        "below. If the user asks to go back to normal or to switch character, call switch_persona.\n\n"
        f"{shared}\n"
    )


def generate(write: bool = True) -> dict[Path, str]:
    """All generated files and their contents; writes them unless write=False."""
    files = {}
    for name in personas():
        for suffix in BASES:
            path = OUT / f"local_{name}{suffix}" / "profile.md"
            files[path] = render(name, suffix)
    if write:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    return files


if __name__ == "__main__":
    written = generate()
    print(f"Wrote {len(written)} persona profiles for: {', '.join(personas())}")
    sys.exit(0)
